name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure this line correctly points to your requirements.txt

    - name: Run script and check output
      run: |
        output=$(python iengine.py test_HornKB.txt FC)
        echo "Output: $output"
        if [[ "$output" == "YES; a, b, p2, p3, p1, c, e, f, d" ]]; then
          echo "Output is correct"
        else
          echo "Output is incorrect"
          exit 1  # This will fail the workflow if output is not as expected
        fi  # Closing the if statement with fi
      shell: bash
      
    - name: Check output
      run: |
        echo "Script execution completed"
