name: Python application test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have any dependencies, install them here
        # pip install -r requirements.txt

    - name: Run script
      run: python iengine.py test_HornKB.txt BC

    - name: Check output
      run: |
        # Add any commands to check outputs or conditions after script execution
        echo "Script execution completed"
